templateInherit/urls.py
from django.contrib import admin
from django.urls import path,include
from templateapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('app/',include('templateapp.urls')),
]

templateapp/urls.py
from django.urls import path
from templateapp import views
app_name='app'
urlpatterns = [
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='con'),
]

templateapp/models.py
from django.db import models


class feedback(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=250)
    message = models.TextField()
    added_on = models.DateTimeField(auto_now_add=True)
    changed_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

templateapp/views.py
from django.shortcuts import render
from templateapp.models import feedback

def home(request):
    return render(request,'home.html')

def about(request):
    return render(request,'about.html')

def contact(request):
    if request.method == 'POST':
        n = request.POST['name']
        e = request.POST['email']
        m = request.POST['message']

        all_data = feedback(name=n,email=e,message=m)
        all_data.save()
        return render(request,'contact.html',{'status':'Data Saved!!'})
    return render(request,'contact.html')

templates/about.html
{% extends "base.html"%}
{% load staticfiles %}
{% block style %}
<style>
h1{
    color:red;
}
</style>
{% endblock %}

{% block body %}
<h1>HELLO IT IS ABOUT PAGE</h1>
{%endblock%}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BASE PAGE</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">

    {% block style %}

    {% endblock %}
</head>
<body>
    <div class='container-fluid'>
        <div class='row'>
            <div class='col-md-12 px-0'>
                <nav class='navbar navbar-dark bg-warning navbar-expand'>
                    <a href="{% url 'home'%}" class='navbar-brand'>Logo</a>
                    <ul class='navbar navbar-nav mx-auto'>
                        <li class='nav-item'>
                            <a href="{% url 'home'%}" class='nav-link'>Home</a>
                        </li>
                        <li class='nav-item'>
                            <a href="{% url 'app:about'%}" class='nav-link'>About</a>
                        </li>
                        <li class='nav-item'>
                            <a href="{% url 'app:con'%}" class='nav-link'>Contact</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>  
        <div class='row'>
            <div class='col-md-3 bg-dark  text-center py-4' style=''>
                <img src="{% static 'images/img4.jpg'%}" height='100' width='100' class='rounded-circle'>
                <div class='py-5 my-5 text-light'>
                    <p>View Profile</p>
                    <p>Change Password</p>
                    <p>Logout</p>
                </div>
            </div>
            <div class='col-md-9'>
                {% block body %}
                {% endblock %}
            </div>
        </div>
        <!-- FOOTER -->
        <div class='row'>
            <div class='col-md-12 bg-warning py-4 text-center text-light'>
                <p>
                    &copy; | All right reserverd
                    Designed By:Your Name
                </p>
            </div>
        </div>
    </div>
</body>
</html>

templates/contact.html
{% extends "base.html"%}
{% block body %}
<div class="row">
    <div class="col-md-12">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3430.056119523628!2d76.69247711461036!3d30.71682269345137!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390fee5a42944be3%3A0xb713d3a3e26a89c1!2sSachTech+Solution+Pvt.+Ltd.!5e0!3m2!1sen!2sin!4v1555666003738!5m2!1sen!2sin" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
    <div class='col-md-5 mx-auto my-3'>
        <h2>LEAVE YOUR FEEDBACK</h2>
        <div style='height:2px;width:30%;background:orange;'></div>
    </div>
</div>
<div class='row'>
    <div class='col-md-6 mx-auto'>
        {% if status %}
        <h2 class='alert alert-success'>{{status}}</h2>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class='form-group'>
                <input type="text" name="name" placeholder='Enter Name' class='form-control'/>
            </div>
            <div class='form-group'>
                <input type="email" name="email" placeholder='Enter Email Address' class='form-control'/>
            </div>
            <div class='form-group'>
                <textarea name="message" rows="10" class='form-control' placeholder='Leave Message Here'></textarea>
            </div>
            <div class='form-group'>
                <input type="submit" class='btn btn-warning' style='width:30%;border-radius:20px;'>
            </div>
               
        </form>
    </div>
</div>

{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block body %}

<h1>THIS IS A HOMEPAGE</h1>
<p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque excepturi fuga, repudiandae, doloremque modi, deleniti id rem nobis optio eius voluptatem assumenda fugiat minima corrupti sint consequuntur vel incidunt ullam.
</p>

{% endblock %}